version: '3'
services:
  proxy:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./static/:/srv/static/:Z"
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
      - "./proxy/sites-enabled/:/etc/nginx/sites-enabled/"
      - "../keys/tdn.crt:/etc/ssl/tdn.crt"
      - "../keys/tdn.key:/etc/ssl/tdn.key"
    links:
      - blog
  blog:
    image: ghost:2.2.2-alpine
    volumes:
      - "../blog-data/:/var/lib/ghost/content"
