version: 2
jobs:
  build:
    working_directory: ~/ci
    docker:
      - image: library/ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install pre-reqs
          command: |
            apt update && apt install -y build-essential openssh-client python3 python3-pip
            pip3 install ansible
      - run:
          name: Write keys
          command: |
            make write_key
            make write_fingerprint
      - run:
          name: Run ansible playbook
          command: |
            ansible-playbook \
              --inventory deploy/production.inventory \
              --key deploy/id_rsa \
              deploy/site.yml
  renew_ssl:
    working_directory: ~/ci
    docker:
      - image: library/ubuntu:18.04
    steps:
      - checkout
      - run:
          name: TEST
          command: ls -ltr

workflows:
  version: 2
  renew_ssl:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - renew_ssl
