version: 2
jobs:
  build:
    working_directory: ~/ci
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: library/ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Test command
          command: |
            grep -v "tnewp.org" ~/.ssh/known_hosts > ~/.ssh/known_hosts.tmp
            apt update && apt install -y build-essential openssh-client
            ls -ltr
            pwd
            make write_key
            make write_fingerprint
            ssh -i deploy/id_rsa deploy@tnewp.org sudo whoami
