version: 2
jobs:
  Deploy to production:
    working_directory: ~/ci
    docker:
      - image: library/ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install pre-reqs
          command: |
            apt update && apt install -y build-essential rsync openssh-client python3 python3-pip
            pip3 install ansible
      - run:
          name: Write keys
          command: |
            make write_key
            make write_fingerprint
      - run:
          name: Run ansible playbook
          command: |
            ansible-playbook \
              --inventory deploy/production.inventory \
              --key deploy/id_rsa \
              deploy/site.yml
  Renew SSL:
    working_directory: ~/ci
    docker:
      - image: library/ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install Make
          commans: apt-get install build-essential
      - run:
          name: Write keys
          command: |
            make write_key
            make write_fingerprint
      - run:
          name: Run ansible playbook
          command: |
            ansible-playbook \
              --inventory deploy/production.inventory \
              --key deploy/id_rsa \
              deploy/renew_cert.yml

workflows:
  version: 2
  Renew SSL:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - Renew SSL
  Deploy:
    jobs:
      - Deploy to production:
          filters:
            branches:
              only:
                - master
