version: 2
jobs:
  build:
    working_directory: ~/ci
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: library/ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Test command 1
          command: |
            mkdir -p ~/.ssh/
            touch ~/.ssh/known_hosts
      - run:
          name: Test command 2
          command: |
            cat ~/.ssh/known_hosts
            grep -v "tnewp.org" ~/.ssh/known_hosts > ~/.ssh/known_hosts.tmp
      - run:
          name: Test command 3
          command: |
            apt update && apt install -y build-essential openssh-client
            ls -ltr
            pwd
      - run:
          name: Test command 4
          command: |
            make write_key
            make write_fingerprint
            ssh -i deploy/id_rsa deploy@tnewp.org sudo whoami
