version: 2
jobs:
  deploy:
    working_directory: ~/ci
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: library/ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install pre-reqs
          command: |
            apt update && apt install -y build-essential openssh-client python3 python3-pip
            pip3 install ansible
      - run:
          name: Run ansible playbook
          command: |
            make write_key
            make write_fingerprint
            ssh -i deploy/id_rsa deploy@tnewp.org sudo hostname
            ansible --inventory deploy/production.inventory --key deploy/id_rsa deploy/site.yml
