---
- hosts: all
  become: true
  remote_user: deploy
  tasks:
    - name: Renew ssl certificate
      shell: certbot --force-renewal renew

    - name: Ensure keys directory exists
      file:
        path: /home/deploy/keys/
        owner: deploy
        group: deploy
        state: directory

    - name: Copy new certificate
      copy:
        src: /etc/letsencrypt/live/tdn.sh-0002/privkey.pem
        dest: /home/deploy/keys/tdn.key
        owner: deploy
        group: deploy
        remote_src: yes

    - name: Copy new certificate
      copy:
        src: /etc/letsencrypt/live/tdn.sh-0002/fullchain.pem
        dest: /home/deploy/keys/tdn.crt
        owner: deploy
        group: deploy
        remote_src: yes

    - name: Restart nginx
      shell: "docker-compose restart {{ item }}"
      args:
        chdir: /home/deploy/site
      with_items:
        - proxy
