---
- hosts: all
  become: true
  remote_user: deploy
  tasks:

  - name: Install rsync
    apt:
      name: rsync
      state: present

  - name: Copy site directory to remote host
    synchronize:
      delete: yes
      src: ../site
      dest: /home/deploy/

  - name: Start docker-compose process
    shell: docker-compose up -d
    args:
      chdir: /home/deploy/site

  - name: Restart nginx
    shell: "docker-compose restart {{ item }}"
    args:
      chdir: /home/deploy/site
    with_items:
      - proxy
