---
- hosts: all
  become: true
  remote_user: deploy
  tasks:

  - name: Copy site directory to remote host
    copy:
      src: ../site
      dest: /home/deploy/
      owner: deploy
      group: deploy

  - name: Start docker-compose process
    shell: docker-compose up -d --build
    args:
      chdir: /home/deploy
