---
- hosts: all
  become: true
  remote_user: deploy
  tasks:

  - name: Copy site directory to remote host
    copy:
      src: ../site
      dest: /home/deploy/
      owner: deploy
      group: deploy

  - name: Install software properties common
    apt:
      name: software-properties-common
      update_cache: yes
      state: present

  - name: Add certbot repo
    apt_repository:
      repo: ppa:certbot/certbot

  - name: Install software properties common
    apt:
      name: python-certbot-nginx
      update_cache: yes
      state: present

  - name: Start docker-compose process
    shell: docker-compose up -d --build
    args:
      chdir: /home/deploy/site
